steps:
  # Build the container image with environment-specific build arguments
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ENV_NAME="production"
        if [ "$BRANCH_NAME" == "staging" ]; then
          ENV_NAME="staging"
        fi
        docker build \
          -t gcr.io/$PROJECT_ID/motokage-studio:$BRANCH_NAME \
          --build-arg VITE_APP_ENV=$ENV_NAME \
          .

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/motokage-studio:$BRANCH_NAME']

  # Deploy to Cloud Run based on branch
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" == "main" ]; then
          gcloud run deploy motokage-studio \
            --image gcr.io/$PROJECT_ID/motokage-studio:$BRANCH_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
        else
          gcloud run deploy motokage-staging \
            --image gcr.io/$PROJECT_ID/motokage-studio:$BRANCH_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --tag staging
        fi

images:
  - 'gcr.io/$PROJECT_ID/motokage-studio:$BRANCH_NAME'

options:
  logging: CLOUD_LOGGING_ONLY